sonar.projectKey=utkarshstudent75-gif_entreprise-IT-Operations-automation-platform
sonar.organization=utkarshstudent75-gif

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8