apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.grafana.storageClassName }}
  storageClassName: {{ .Values.grafana.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.storage | quote }}
