apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090
        isDefault: true
        editable: false
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: EITOAP
        orgId: 1
        type: file
        disableDeletion: true
        editable: false
        updateIntervalSeconds: 30
        options:
          path: /etc/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
data:
  application.json: |
{{ .Files.Get "dashboards/application.json" | indent 4 }}
  kubernetes.json: |
{{ .Files.Get "dashboards/kubernetes.json" | indent 4 }}
