[pytest]
testpaths = tests
pythonpath = .
addopts = --import-mode=importlib --cov=app/services --cov=app/repositories --cov=app/api --cov=app/models --cov=app/core --cov-config=.coveragerc --cov-report=term --cov-report=html:coverage/html --cov-report=xml:coverage/coverage.xml
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::RuntimeWarning
