apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eitoap-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/utkarshstudent75-gif/entreprise-IT-Operations-automation-platform.git'
      targetRevision: master
      ref: repo
    - repoURL: 'https://github.com/utkarshstudent75-gif/entreprise-IT-Operations-automation-platform.git'
      targetRevision: master
      path: deploy/helm/frontend
      helm:
        valueFiles:
          - $repo/deploy/helm/values/dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
