apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# In the local overlay, we can customize settings or add local specific resources if needed.
# For example, override the image tags to 'latest' or use local registry.
patches:
  - target:
      kind: Deployment
      name: backend-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: frontend-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
