apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# In the dev overlay, we can customize settings for dev environment.
patches:
  - target:
      kind: Deployment
      name: backend-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: frontend-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
