apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.backendService }}
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.ingress.backendService }}.{{ .Values.networkPolicy.backendNamespace }}.svc.cluster.local
  ports:
    - port: {{ .Values.ingress.backendPort }}
      targetPort: {{ .Values.ingress.backendPort }}
      name: http
