apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ if and .Values.frontend .Values.frontend.replicaCount }}{{ .Values.frontend.replicaCount }}{{ else }}{{ .Values.replicaCount }}{{ end }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        {{- toYaml .Values.securityContext.pod | nindent 8 }}
      containers:
        - name: frontend
          image: "{{ if and .Values.frontend .Values.frontend.image }}{{ .Values.frontend.image.repository }}{{ else }}{{ .Values.image.repository }}{{ end }}:{{ if and .Values.frontend .Values.frontend.image }}{{ .Values.frontend.image.tag }}{{ else }}{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ if and .Values.frontend .Values.frontend.image }}{{ .Values.frontend.image.pullPolicy }}{{ else }}{{ .Values.image.pullPolicy }}{{ end }}
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            {{- toYaml .Values.securityContext.container | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
          envFrom:
            - configMapRef:
                name: frontend-config
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
