{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow inbound traffic on port 8080 from Ingress Controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.ingressNamespace | default "ingress" }}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    # Allow DNS requests
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow egress TCP traffic to backend pods in backend namespace
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.backendNamespace | default "backend" }}
          podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: 8000
{{- end }}
