apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.backendNamespace }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}
  SMS_API_KEY: {{ .Values.secrets.smsApiKey | b64enc | quote }}
  SMS_ACCOUNT_SID: {{ .Values.secrets.smsAccountSid | b64enc | quote }}
