apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# In the prod overlay, we can customize settings for production environment (e.g., higher replicas).
patches:
  - target:
      kind: Deployment
      name: backend-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: frontend-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
