"""create_new_models

Revision ID: 26ee6594045c
Revises: c1f373514a52
Create Date: 2026-07-21 07:35:14.158123

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26ee6594045c"
down_revision: Union[str, Sequence[str], None] = "c1f373514a52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mfa_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mfa_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mfa_requests_id"), "mfa_requests", ["id"], unique=False)
    op.create_index(
        op.f("ix_mfa_requests_requested_by"),
        "mfa_requests",
        ["requested_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mfa_requests_status"), "mfa_requests", ["status"], unique=False
    )
    op.create_table(
        "software_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("software_name", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_software_requests_id"), "software_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_software_requests_requested_by"),
        "software_requests",
        ["requested_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_software_requests_status"),
        "software_requests",
        ["status"],
        unique=False,
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tickets_created_by"), "tickets", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_tickets_id"), "tickets", ["id"], unique=False)
    op.create_index(op.f("ix_tickets_status"), "tickets", ["status"], unique=False)
    op.create_table(
        "workflows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflows_created_by"), "workflows", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_workflows_id"), "workflows", ["id"], unique=False)
    op.create_index(op.f("ix_workflows_status"), "workflows", ["status"], unique=False)
    op.create_index(
        op.f("ix_workflows_workflow_type"), "workflows", ["workflow_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflows_workflow_type"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_status"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_id"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_created_by"), table_name="workflows")
    op.drop_table("workflows")
    op.drop_index(op.f("ix_tickets_status"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_created_by"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_software_requests_status"), table_name="software_requests")
    op.drop_index(
        op.f("ix_software_requests_requested_by"), table_name="software_requests"
    )
    op.drop_index(op.f("ix_software_requests_id"), table_name="software_requests")
    op.drop_table("software_requests")
    op.drop_index(op.f("ix_mfa_requests_status"), table_name="mfa_requests")
    op.drop_index(op.f("ix_mfa_requests_requested_by"), table_name="mfa_requests")
    op.drop_index(op.f("ix_mfa_requests_id"), table_name="mfa_requests")
    op.drop_table("mfa_requests")
    # ### end Alembic commands ###
