"""Create password_reset_requests table

Revision ID: 7f8e9d6c2b1a
Revises: 63d1536ae57a
Create Date: 2026-07-17 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f8e9d6c2b1a"
down_revision: Union[str, Sequence[str], None] = "63d1536ae57a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("otp", sa.String(length=6), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "is_used", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_requests_user_id"),
        "password_reset_requests",
        ["user_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_password_reset_requests_user_id_users",
        "password_reset_requests",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_password_reset_requests_user_id_users",
        "password_reset_requests",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_password_reset_requests_user_id"), table_name="password_reset_requests"
    )
    op.drop_table("password_reset_requests")
    # ### end Alembic commands ###
