apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eitoap-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/utkarshstudent75-gif/entreprise-IT-Operations-automation-platform.git'
    targetRevision: feature/gitops-argocd-deployment
    path: deploy/argocd/applications
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
