namespace: backend

replicaCount: 2

image:
  repository: enterpriseitoperationsplatformdev1bab46e1.azurecr.io/backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 80
  memoryUtilization: 80

pdb:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: true
  ingressNamespace: ingress
  monitoringNamespace: monitoring
